# Generated by Django 5.0.6 on 2024-07-11 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
