# Generated by Django 5.0.6 on 2024-07-11 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanpage', '0003_comment_newsarticle_photo_video_alter_movie_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='auther',
            new_name='author',
        ),
    ]
