# Generated by Django 5.0.6 on 2024-07-11 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanpage', '0004_rename_auther_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_data',
            new_name='created_date',
        ),
    ]
