# Generated by Django 5.0.6 on 2024-07-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanpage', '0005_rename_created_data_comment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_link',
            field=models.URLField(blank=True),
        ),
    ]
