# Generated by Django 5.0.6 on 2024-07-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanpage', '0006_alter_movie_trailer_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='read_more_link',
            field=models.URLField(blank=True),
        ),
    ]
