# Generated by Django 5.0.6 on 2024-07-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanpage', '0008_movielist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieList',
        ),
    ]
