# Generated by Django 5.0.7 on 2024-07-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanpage', '0011_award_biography_filmography_relatedlinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biography',
            name='content',
        ),
        migrations.AddField(
            model_name='biography',
            name='about',
            field=models.TextField(default='About Dhanush content here.'),
        ),
        migrations.AddField(
            model_name='biography',
            name='early_life',
            field=models.TextField(default='Early life content here.'),
        ),
        migrations.AddField(
            model_name='biography',
            name='movie_career_actor',
            field=models.TextField(default='Movie career as an actor content here.'),
        ),
        migrations.AddField(
            model_name='biography',
            name='movie_career_director',
            field=models.TextField(default='Movie career as a director content here.'),
        ),
        migrations.AddField(
            model_name='biography',
            name='movie_career_producer',
            field=models.TextField(default='Movie career as a producer content here.'),
        ),
        migrations.AddField(
            model_name='biography',
            name='personal_life',
            field=models.TextField(default='Personal life content here.'),
        ),
        migrations.AlterField(
            model_name='biography',
            name='title',
            field=models.CharField(default='Biography of Dhanush', max_length=200),
        ),
    ]
