# Generated by Django 5.0.7 on 2024-07-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanpage', '0012_remove_biography_content_biography_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='image',
            field=models.ImageField(default='default_biography_image.jpg', upload_to='Biography/'),
        ),
    ]
