# Generated by Django 5.0.7 on 2024-07-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanpage', '0013_biography_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
