# Generated by Django 5.0.7 on 2024-07-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanpage', '0014_movie_upcoming'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='year',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='award',
            name='description',
            field=models.TextField(default='Description of the award.'),
        ),
        migrations.AlterField(
            model_name='award',
            name='title',
            field=models.CharField(default='Award Title', max_length=200),
        ),
    ]
