# Generated by Django 5.0.7 on 2024-07-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanpage', '0015_award_year_alter_award_description_alter_award_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='latest',
            field=models.BooleanField(default=False),
        ),
    ]
