# Generated by Django 5.0.7 on 2024-07-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanpage', '0016_movie_latest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieList',
        ),
    ]
