# Generated by Django 5.0.7 on 2024-07-12 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanpage', '0018_remove_movie_latest_remove_movie_upcoming_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='poster',
            new_name='image',
        ),
    ]
