# Generated by Django 5.0.7 on 2024-07-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanpage', '0019_rename_poster_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
