# Generated by Django 5.0.7 on 2024-07-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanpage', '0022_alter_movie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
