# Generated by Django 5.0.7 on 2024-07-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanpage', '0023_alter_award_year_alter_photo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='description',
        ),
        migrations.AddField(
            model_name='award',
            name='category',
            field=models.CharField(default='Award Category', max_length=200),
        ),
        migrations.AddField(
            model_name='award',
            name='film',
            field=models.CharField(default='Film', max_length=200),
        ),
    ]
