# Generated by Django 5.0.7 on 2024-07-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanpage', '0025_award_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='award',
            name='film',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='award',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
