# Generated by Django 5.0.7 on 2024-07-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanpage', '0026_alter_award_category_alter_award_film_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_link',
            field=models.URLField(blank=True),
        ),
    ]
