# Generated by Django 5.0.7 on 2024-07-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanpage', '0027_alter_video_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='profile',
            field=models.ImageField(default='default_biography_image2.jpg', upload_to='Biography/'),
        ),
    ]
